// Auto-generated by: supabase gen types typescript --project-id <id> > src/common/types/database.ts
// Manually maintained here until Supabase CLI is wired into CI.
// Run `npx supabase gen types typescript` to regenerate after schema changes.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          password_hash: string | null
          provider: 'local' | 'google' | 'facebook'
          provider_id: string | null
          is_email_verified: boolean
          onboarded: boolean
          interests: string[]
          role: 'USER' | 'ARTIST' | 'MODERATOR' | 'ADMIN'
          status: 'ACTIVE' | 'SUSPENDED' | 'DELETED'
          token_version: number
          failed_login_attempts: number
          locked_until: string | null
          last_login_at: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          email: string
          password_hash?: string | null
          provider?: 'local' | 'google' | 'facebook'
          provider_id?: string | null
          is_email_verified?: boolean
          onboarded?: boolean
          interests?: string[]
          role?: 'USER' | 'ARTIST' | 'MODERATOR' | 'ADMIN'
          status?: 'ACTIVE' | 'SUSPENDED' | 'DELETED'
          token_version?: number
          failed_login_attempts?: number
          locked_until?: string | null
          last_login_at?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      }
      auth_sessions: {
        Row: {
          id: string
          user_id: string
          refresh_token_hash: string
          user_agent: string | null
          ip_address: string | null
          expires_at: string
          created_at: string
          last_used_at: string
          revoked_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          refresh_token_hash: string
          user_agent?: string | null
          ip_address?: string | null
          expires_at: string
          created_at?: string
          last_used_at?: string
          revoked_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['auth_sessions']['Insert']>
      }
      password_reset_tokens: {
        Row: {
          id: string
          user_id: string
          reset_token_hash: string
          reset_email: string
          reset_attempts: number
          expires_at: string
          used_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          reset_token_hash: string
          reset_email: string
          reset_attempts?: number
          expires_at: string
          used_at?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['password_reset_tokens']['Insert']>
      }
      audit_logs: {
        Row: {
          id: string
          user_id: string | null
          action: string
          ip_address: string | null
          user_agent: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          action: string
          ip_address?: string | null
          user_agent?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['audit_logs']['Insert']>
      }
    }
    Views: Record<string, never>
    // Functions: Record<string, never>
    Functions: {
      increment_reset_attempts: {
        Args: { token_id: string }
        Returns: undefined // or void
      }, 
      increment_token_version: {
        Args: { user_id: string }
        Returns: number
      },
      increment_failed_login_attempts: {
        Args: { user_id: string }
        Returns: undefined
      },
      rotate_session: {
        Args: {
          p_old_session_id: string
          p_user_id: string
          p_new_token_hash: string
          p_user_agent: string | null
          p_ip_address: string | null
          p_expires_at: string
        }
        Returns: Json // or the specific Row type if you prefer
      }
    },
    Enums: {
      user_role: 'USER' | 'ARTIST' | 'MODERATOR' | 'ADMIN'
      user_status: 'ACTIVE' | 'SUSPENDED' | 'DELETED'
      auth_provider: 'local' | 'google' | 'facebook'
    }
  }
}